version: "3.8"
services:
  retos-spring-app:
    build: .
    container_name: retos-spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/retosdb
      - SPRING_DATASOURCE_USERNAME=retos_user
      - SPRING_DATASOURCE_PASSWORD=retos_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=U7t8C34aqstQ6soj1Bub9JYk7Y4BnNT3
      - JWT_EXPIRATION_SECONDS=3600

      # 🔹 Configuración Gmail
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=londgav01@gmail.com
      - SPRING_MAIL_PASSWORD=dgcp rgve sazl arhk   # tu app password de Gmail
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true

    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: retos-postgres
    environment:
      - POSTGRES_DB=retosdb
      - POSTGRES_USER=retos_user
      - POSTGRES_PASSWORD=retos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

