spring.application.name=servidor-web-spring

# Auth0 configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-30i54ne2co01oqar.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://servidorweb-api