# Datasource (los valores reales via env vars en docker-compose)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/retosdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:retos_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:retos_pass}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET:U7t8C34aqstQ6soj1Bub9JYk7Y4BnNT3}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}

# Mail (MailHog)
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
